### ISSUE TITLE
Submit this to Codeception

### ISSUE THREAD

**Issue by DavertMik** [edno/codeception-dataprovider#2]
It would be cool to have it implemented in the core. 
Just a reminder for you to submit a Pull Request :)

**Comment by mikeuding** [comment]
I would definitely love this

**Comment by edno** [comment]
PR submitted but Nitpick-CI is not happy... let's wait for the CI results before doing some code :lipstick:

**Comment by edno** [comment]
Todo once the PR has been merge to Codeception 2.2  
- [ ] Add Composer conflict version with `codeception/codeception: >2.2.6 `
